import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/redux/providers'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header style={{width: "100%", display: "flex", justifyContent: "space-around", padding: "3rem"}}>
            <Link href='/users'>Users</Link>
            <Link href='/products'>Products</Link>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  )
}
